export const FETCH_ALL_CONTACTS_REQUESTED = 'FETCH_ALL_CONTACTS_REQUESTED';
export const FETCH_ALL_CONTACTS_SUCCEEDED = 'FETCH_ALL_CONTACTS_SUCCEEDED';
export const FETCH_ALL_CONTACTS_FAILED = 'FETCH_ALL_CONTACTS_FAILED';
export const DELETE_CONTACT_REQUESTED = 'DELETE_CONTACT_REQUESTED';
export const DELETE_CONTACT_SUCCEEDED = 'DELETE_CONTACT_SUCCEEDED';
export const DELETE_CONTACT_FAILED = 'DELETE_CONTACT_FAILED';
